apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-server-{{ .Values.Instance }}-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: web-server-{{ .Values.Instance }}-sc
