apiVersion: v1
kind: ConfigMap
metadata:
  name: customize
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    app: osg-frontier-squid
data:
  customize.sh: |-
    #!/bin/bash

    awk --file `dirname $0`/customhelps.awk --source '{
    setoption("cache_mem", "{{ .Values.SquidConf.CacheMem }} MB")
    setoptionparameter("cache_dir", 3, "{{ .Values.SquidConf.CacheSize }}")
    print
    }'