apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-frontier-squid-{{ .Values.Instance }}-configuration
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    app: osg-frontier-squid
    tag: {{ .Values.Instance }}
data:
  customize.sh: |-
    #!/bin/bash

    awk --file `dirname $0`/customhelps.awk --source '{
    setoption("acl NET_LOCAL src", "0.0.0.0/0")
    setoption("http_port", "{{ .Values.Service.Port }}")
    setoption("cache_mem", "{{ .Values.SquidConf.CacheMem }} MB")
    setoptionparameter("cache_dir", 3, "{{ .Values.SquidConf.CacheSize }}")
    setoption("visible_hostname", "osg-frontier-squid-{{ .Values.Instance }}")
    print
    }'