apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
  labels:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-frontier-squid.name" . }}
      chart: {{ template "osg-frontier-squid.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}

  template:
    metadata:
      labels:
        app: {{ template "osg-frontier-squid.name" . }}
        chart: {{ template "osg-frontier-squid.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      nodeSelector:
        storage: "local"
      containers:
      - name: osg-frontier-squid
        image: slateci/osg-frontier-squid:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3128
          name: squid
        volumeMounts:
        - mountPath: /etc/squid/customize.sh
          subPath: customize.sh
          name: osg-frontier-squid-{{ .Values.Instance }}-configuration
        - mountPath: /var/cache/squid
          subPath: osg-frontier-squid-{{ .Values.Instance }}-cache
          name: osg-frontier-squid-{{ .Values.Instance }}-pvc
        - mountPath: /var/log/squid
          name: varlogsquid
      - name: filebeat
        image: elastic/filebeat:6.4.1
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: atlas-kibana.mwt2.org
        - name: ELASTICSEARCH_PORT
          value: "9200"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: filebeat-{{ .Values.Instance }}-config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: filebeat-{{ .Values.Instance }}-inputs
          mountPath: /usr/share/filebeat/inputs.d
          readOnly: true
        - name: filebeat-{{ .Values.Instance }}-pvc
          mountPath: /usr/share/filebeat/data
        - name: varlogsquid
          mountPath: /var/log/squid
      volumes:
        - name: osg-frontier-squid-{{ .Values.Instance }}-configuration
          configMap:
            name: osg-frontier-squid-{{ .Values.Instance }}-configuration
            items:
              - key: customize.sh
                path: customize.sh
            defaultMode: 0755
        - name: osg-frontier-squid-{{ .Values.Instance }}-pvc
          persistentVolumeClaim:
            claimName: osg-frontier-squid-{{ .Values.Instance }}-pvc
        - name: filebeat-{{ .Values.Instance }}-config
          configMap:
            defaultMode: 0600
            name: filebeat-{{ .Values.Instance }}-config
        - name: filebeat-{{ .Values.Instance }}-inputs
          configMap:
            defaultMode: 0600
            name: filebeat-{{ .Values.Instance }}-inputs
        # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
        - name: filebeat-{{ .Values.Instance }}-pvc
          persistentVolumeClaim:
            claimName: filebeat-{{ .Values.Instance }}-pvc
        - name: varlogsquid
          emptyDir: {}
