apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
  labels:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    tag: {{ .Values.Tag }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-frontier-squid.name" . }}
      chart: {{ template "osg-frontier-squid.chart" . }}
      release: {{ .Release.Name }}
      tag: {{ .Values.Tag }}

  template:
    metadata:
      labels:
        app: {{ template "osg-frontier-squid.name" . }}
        chart: {{ template "osg-frontier-squid.chart" . }}
        release: {{ .Release.Name }}
        tag: {{ .Values.Tag }}
    spec:
      containers:
      - name: osg-frontier-squid
        image: slateci/osg-frontier-squid:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3128
          name: squid
        volumeMounts:
        - mountPath: /etc/squid/customize.sh
          subPath: customize.sh
          name: customize-volume
      volumes:
        - name: customize-volume
          configMap:
            name: osg-frontier-squid-{{ .Values.Tag }}-configuration
            items:
              - key: customize.sh
                path: customize.sh
            defaultMode: 0755

