apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
  labels:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-frontier-squid.name" . }}
      chart: {{ template "osg-frontier-squid.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}

  template:
    metadata:
      labels:
        app: {{ template "osg-frontier-squid.name" . }}
        chart: {{ template "osg-frontier-squid.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      nodeSelector:
        storage: "local"
      containers:
      - name: osg-frontier-squid
        image: slateci/osg-frontier-squid:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3128
          name: squid
        volumeMounts:
        - mountPath: /etc/squid/customize.sh
          subPath: customize.sh
          name: osg-frontier-squid-{{ .Values.Instance }}-configuration
        - mountPath: /var/cache/squid
          subPath: osg-frontier-squid-{{ .Values.Instance }}-cache
          name: osg-frontier-squid-{{ .Values.Instance }}-pvc
        - mountPath: /var/log/squid
          name: varlog
      - name: fluent-bit
        image: fluent/fluent-bit:0.13.4
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: fluent-bit-{{ .Values.Instance }}-config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log/squid
      volumes:
        - name: osg-frontier-squid-{{ .Values.Instance }}-configuration
          configMap:
            name: osg-frontier-squid-{{ .Values.Instance }}-configuration
            items:
              - key: customize.sh
                path: customize.sh
            defaultMode: 0755
        - name: osg-frontier-squid-{{ .Values.Instance }}-pvc
          persistentVolumeClaim:
            claimName: osg-frontier-squid-{{ .Values.Instance }}-pvc
        - name: fluent-bit-{{ .Values.Instance }}-config
          configMap:
            name: fluent-bit-{{ .Values.Instance }}-config
        - name: varlog
          emptyDir: {}





