apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
  labels:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-frontier-squid.name" . }}
      chart: {{ template "osg-frontier-squid.chart" . }}
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ template "osg-frontier-squid.name" . }}
        chart: {{ template "osg-frontier-squid.chart" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: osg-frontier-squid
        image: slateci/osg-frontier-squid:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3128
          name: squid
        volumeMounts:
        - mountPath: /etc/squid/customize.sh
          subPath: customize.sh
          name: osg-frontier-squid-{{ .Values.Tag }}-customization
        - mountPath: /var/cache/squid
          name: osg-frontier-squid-{{ .Values.Tag }}-pv
      volumes:
        - name: osg-frontier-squid-{{ .Values.Tag }}-customization
          configMap:
            name: osg-frontier-squid-{{ .Values.Tag }}-customization
            items:
              - key: customize.sh
                path: customize.sh
            defaultMode: 0755
        - name: osg-frontier-squid-{{ .Values.Tag }}-pv
          persistentVolumeClaim:
            claimName: osg-frontier-squid-{{ .Values.Tag }}-claim


