apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-{{ .Values.Instance }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        # Mounted `filebeat-inputs` configmap:
        path: ${path.config}/inputs.d/*.yml
        # Reload inputs configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    # To enable hints based autodiscover, remove `filebeat.config.inputs` configuration and uncomment this:
    #filebeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      hints.enabled: true

    processors:
    - dissect:
        tokenizer: "%{}"
        field: "message"
        target_prefix: "dissect"

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      protocol: http
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-{{ .Values.Instance }}-inputs
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
data:
  kubernetes.yml: |-
    - type: log
      paths:
        - "/var/log/squid/*.log"
      tags: ["osg-frontier-squid","osg-frontier-squid-{{ .Values.Instance }}"]