apiVersion: v1
kind: PersistentVolume
metadata:
  name: osg-frontier-squid-{{ .Values.Tag }}-pv
spec:
  capacity:
    storage: {{ .Values.SquidConf.CacheSize }}Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: {{ .Values.CacheMount }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - local