kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: osg-frontier-squid-{{ .Values.Tag }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.SquidConf.CacheSize }}Mi
  storageClassName: local-storage