kind: Service
apiVersion: v1
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
spec:
  type: {{ .Values.Service.Type }} # parametrize for load balancer option
  selector:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    tag: {{ .Values.Tag }}
  ports:
  - port: {{ .Values.Service.Port }}
    targetPort: squid

# Needs customized name for deployments
# Could have multiple deployments in the same namespace