kind: Service
apiVersion: v1
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
spec:
  {{ if .Values.Service.ExternallyVisible }}
  type: LoadBalancer
  {{ else }}
  type: ClusterIP
  {{ end }}
  selector:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
  ports:
  - port: {{ .Values.Service.Port }}
    targetPort: squid
