apiVersion: v1
kind: Pod
metadata:
  name: web-server-{{ .Values.Instance }}
spec:
  containers:
   - name: web-server
     image: nginx:latest
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /localStorage
         name: mypvc
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: web-server-{{ .Values.Instance }}-pvc
       readOnly: true
