apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-server-{{ .Values.Instance }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.LocalStorage.Size }}Gi
  storageClassName: nfs-provisioner
