apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{ if .Values.Service.ExternallyVisible }}
  type: LoadBalancer
  {{ else }}
  type: ClusterIP
  {{ end }}
  externalTrafficPolicy: Local
  ports:
    - name: service
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ template "grafana.name" . }}
    release: {{ .Release.Name }}
